-- ============================================================
--  Rabimbox – SKLADIŠČNA APLIKACIJA: shema
--  Zaženi v Supabase: Dashboard -> SQL Editor -> prilepi -> Run
-- ------------------------------------------------------------
--  Idempotentno: varno je zagnati večkrat.
--  Nadgrajuje obstoječe tabele (kupci, skatle, narocila) in
--  doda nove: skladisce_lokacije, narocnine, skladisce_dogodki.
--
--  Kaj pokriva:
--   * Bar kode: vsaka škatla svojo kodo (skatle.koda) + lokacija
--   * Številke naročil (narocila.stevilka) in strank (kupci.stevilka_stranke)
--   * Naročnine od–do (tabela narocnine: datum_od / datum_do / status)
--   * Upravljanje s škatlami (status, lokacija, dnevnik skeniranj)
--
--  OPOMBA glede dostopa: skladiščna aplikacija naj se povezuje s
--  SERVICE ROLE ključem (strežniško) – ta obide RLS. Stranke prek
--  panela vidijo le svoje naročnine (RLS spodaj).
-- ============================================================

-- ------------------------------------------------------------
-- 0) Pomožna funkcija za RLS: id trenutnega kupca
-- ------------------------------------------------------------
create or replace function public.my_kupec_id()
returns bigint
language sql stable security definer
set search_path = public
as $$
  select id from public.kupci
  where lower(email) = lower(auth.jwt() ->> 'email')
  limit 1;
$$;
grant execute on function public.my_kupec_id() to authenticated;

-- generična funkcija za osveževanje updated_at
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end;
$$;

-- ============================================================
-- 1) ŠTEVILKE STRANK IN NAROČIL (človeku berljive)
-- ============================================================
-- Številka stranke: ST-00001, ST-00002, ...
alter table public.kupci   add column if not exists stevilka_stranke text;
create sequence if not exists public.kupci_stevilka_seq;

create or replace function public.set_stevilka_stranke()
returns trigger language plpgsql as $$
begin
  if new.stevilka_stranke is null or new.stevilka_stranke = '' then
    new.stevilka_stranke := 'ST-' || lpad(nextval('public.kupci_stevilka_seq')::text, 5, '0');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_kupci_stevilka on public.kupci;
create trigger trg_kupci_stevilka before insert on public.kupci
  for each row execute function public.set_stevilka_stranke();

-- obstoječim strankam dodeli številko
update public.kupci
   set stevilka_stranke = 'ST-' || lpad(nextval('public.kupci_stevilka_seq')::text, 5, '0')
 where stevilka_stranke is null or stevilka_stranke = '';

create unique index if not exists kupci_stevilka_stranke_uidx
  on public.kupci (stevilka_stranke);

-- Številka naročila (checkout jo že ustvarja: RB-YYYY-...). Samo zagotovimo stolpec+indeks.
alter table public.narocila add column if not exists stevilka text;
create index if not exists narocila_stevilka_idx on public.narocila (stevilka);

-- ============================================================
-- 2) SKLADIŠČNE LOKACIJE (regal / polica / pozicija)
-- ============================================================
create table if not exists public.skladisce_lokacije (
  id         bigint generated by default as identity primary key,
  koda       text unique,                 -- nalepka lokacije, npr. "A-01-03"
  regal      text,                        -- npr. "A"
  polica     text,                        -- npr. "01"
  pozicija   text,                        -- npr. "03"
  kapaciteta int,                          -- koliko škatel gre na to mesto
  opis       text,
  created_at timestamptz default now()
);
create index if not exists skladisce_lokacije_koda_idx on public.skladisce_lokacije (koda);

-- ============================================================
-- 3) NAROČNINE (od kdaj do kdaj so odprte)
-- ============================================================
create table if not exists public.narocnine (
  id            bigint generated by default as identity primary key,
  kupec_id      bigint references public.kupci(id) on delete set null,
  narocilo_id   bigint,                     -- povezava na narocila.id (če obstaja)
  tip           text,                       -- 'izposoja' | 'skladiscenje'
  st_boxov      int,
  cena_mesecna  numeric(10,2),
  valuta        text default 'EUR',
  datum_od      date default current_date,  -- začetek naročnine
  datum_do      date,                       -- NULL = še odprta
  status        text default 'aktivna',     -- aktivna | pavza | zakljucena | preklicana
  opomba        text,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);
create index if not exists narocnine_kupec_idx    on public.narocnine (kupec_id);
create index if not exists narocnine_status_idx   on public.narocnine (status);
create index if not exists narocnine_narocilo_idx on public.narocnine (narocilo_id);

drop trigger if exists trg_narocnine_touch on public.narocnine;
create trigger trg_narocnine_touch before update on public.narocnine
  for each row execute function public.touch_updated_at();

-- ============================================================
-- 4) ŠKATLE: bar koda (barkoda), status, lokacija, naročnina
--    OPOMBA: bar koda je obstoječi stolpec "barkoda" (NOT NULL).
-- ============================================================
alter table public.skatle add column if not exists status       text default 'na_zalogi';
  -- na_zalogi | rezervirana | pri_stranki | v_skladiscu | v_transportu | poskodovana | umaknjena
alter table public.skatle add column if not exists lokacija_id  bigint references public.skladisce_lokacije(id) on delete set null;
alter table public.skatle add column if not exists narocnina_id bigint references public.narocnine(id) on delete set null;
alter table public.skatle add column if not exists opomba       text;
alter table public.skatle add column if not exists updated_at   timestamptz default now();

-- samodejna bar koda za prihodnje vnose (RB000001 ...), če ni vpisana
create sequence if not exists public.skatle_barkoda_seq;
create or replace function public.set_barkoda()
returns trigger language plpgsql as $$
begin
  if new.barkoda is null or new.barkoda = '' then
    new.barkoda := 'RB' || lpad(nextval('public.skatle_barkoda_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_skatle_barkoda on public.skatle;
create trigger trg_skatle_barkoda before insert on public.skatle
  for each row execute function public.set_barkoda();

create unique index if not exists skatle_barkoda_uidx on public.skatle (barkoda);
create index if not exists skatle_status_idx   on public.skatle (status);
create index if not exists skatle_lokacija_idx  on public.skatle (lokacija_id);
create index if not exists skatle_narocnina_idx on public.skatle (narocnina_id);

drop trigger if exists trg_skatle_touch on public.skatle;
create trigger trg_skatle_touch before update on public.skatle
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------------
-- 4b) 1000 boxov na zalogi (enkratni zagon)
-- ------------------------------------------------------------
insert into public.skatle (barkoda, status)
select 'RB' || lpad(g::text, 6, '0'), 'na_zalogi'
from generate_series(1, 1000) g
on conflict (barkoda) do nothing;
select setval('public.skatle_barkoda_seq', 1000, true);

-- ------------------------------------------------------------
-- 4c) Samodejno dodeljevanje boxov ob naročilu
--     Ob vnosu v "narocila": ustvari naročnino in dodeli N
--     prostih boxov stranki (status -> rezervirana = za dostavo).
-- ------------------------------------------------------------
create or replace function public.narocilo_dodeli_skatle()
returns trigger language plpgsql security definer set search_path = public as $$
declare n int; nn bigint;
begin
  n := coalesce(nullif(new.st_boxov, 0),
                nullif(regexp_replace(coalesce(new.paket,''), '\D', '', 'g'), '')::int, 0);
  if new.kupec_id is null or n <= 0 then return new; end if;
  insert into public.narocnine(kupec_id, narocilo_id, tip, st_boxov, datum_od, status)
    values (new.kupec_id, new.id, new.tip, n, current_date, 'aktivna')
    returning id into nn;
  with pick as (
    select id from public.skatle
     where status = 'na_zalogi' and kupec_id is null
     order by id limit n for update skip locked
  )
  update public.skatle s
     set kupec_id = new.kupec_id, narocnina_id = nn, status = 'rezervirana', tip_storitve = new.tip, updated_at = now()
    from pick where s.id = pick.id;
  return new;
end;
$$;
drop trigger if exists trg_narocilo_dodeli_skatle on public.narocila;
create trigger trg_narocilo_dodeli_skatle after insert on public.narocila
  for each row execute function public.narocilo_dodeli_skatle();

-- ------------------------------------------------------------
-- 4d) Ob naročilu shrani naslov/poštno/mesto/telefon v kupci
--     (da se ob naslednjem naročilu samodejno napolnijo)
-- ------------------------------------------------------------
create or replace function public.narocilo_posodobi_naslov()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.kupec_id is not null then
    update public.kupci set
      postna_stevilka = coalesce(nullif(new.postna_stevilka,''), postna_stevilka),
      kraj            = coalesce(nullif(new.mesto,''), kraj),
      naslov          = coalesce(nullif(new.naslov,''), naslov),
      telefon         = coalesce(nullif(new.telefon,''), telefon)
    where id = new.kupec_id;
  end if;
  return new;
end;
$$;
drop trigger if exists trg_narocilo_posodobi_naslov on public.narocila;
create trigger trg_narocilo_posodobi_naslov after insert on public.narocila
  for each row execute function public.narocilo_posodobi_naslov();

-- ============================================================
-- 5) DNEVNIK SKENIRANJ / DOGODKI V SKLADIŠČU
-- ============================================================
create table if not exists public.skladisce_dogodki (
  id           bigint generated by default as identity primary key,
  skatla_id    bigint references public.skatle(id) on delete cascade,
  lokacija_id  bigint references public.skladisce_lokacije(id) on delete set null,
  narocnina_id bigint references public.narocnine(id) on delete set null,
  dejanje      text,   -- prevzem | odlozitev | premik | dostava | vrnitev | inventura | poskodba
  status_nov   text,   -- nov status škatle po dogodku (neobvezno)
  uporabnik    text,   -- kdo je skeniral (skladiščnik)
  opomba       text,
  created_at   timestamptz default now()
);
create index if not exists skladisce_dogodki_skatla_idx on public.skladisce_dogodki (skatla_id);
create index if not exists skladisce_dogodki_cas_idx    on public.skladisce_dogodki (created_at);

-- ============================================================
-- 6) RLS (Row Level Security)
-- ------------------------------------------------------------
--  * narocnine: stranka vidi SVOJE (prek panela). Skladiščna
--    aplikacija uporablja service role -> obide RLS.
--  * skladisce_lokacije, skladisce_dogodki: interno (service role),
--    brez javnih pravil.
-- ============================================================
alter table public.narocnine          enable row level security;
alter table public.skladisce_lokacije enable row level security;
alter table public.skladisce_dogodki  enable row level security;

drop policy if exists narocnine_select_own on public.narocnine;
create policy narocnine_select_own on public.narocnine
  for select to authenticated
  using ( kupec_id = public.my_kupec_id() );

-- ============================================================
--  KONEC. Preveri: Table Editor -> nove tabele in stolpci.
-- ============================================================
